export function collectViewerDom(document) {
    const get = (id) => document.getElementById(id);

    const statusEl = get('status');

    return {
        bootLoaderEl: get('bootLoader'),
        bootLoaderBarEl: get('bootLoaderBar'),
        bootLoaderTextEl: get('bootLoaderText'),
        bootLoaderPctEl: get('bootLoaderPct'),
        rootEl: get('viewer'),
        annotateCanvasEl: get('annotateCanvas'),
        annotateToolbarEl: get('annotateToolbar'),
        annoToggleBtn: get('annoToggleBtn'),
        annoVisibleBtn: get('annoVisibleBtn'),
        annoDrawBtn: get('annoDrawBtn'),
        annoColorEl: get('annoColor'),
        annoDashEl: get('annoDash'),
        annoWidthEl: get('annoWidth'),
        annoUndoBtn: get('annoUndoBtn'),
        annoClearBtn: get('annoClearBtn'),
        annoLayerSelectEl: get('annoLayerSelect'),
        annoLayerAddBtn: get('annoLayerAddBtn'),
        dropEl: get('drop'),
        statusEl,
        appbarStatusEl: get('appbarStatus') || statusEl,
        emptyHintEl: get('emptyHint'),
        shadingSel: get('shadingMode'),

        // Sun
        sunHourEl: get('sunHour'),
        sunHourInputEl: get('sunHourInput'),
        sunIntensityEl: get('sunIntensity'),
        sunIntensityInputEl: get('sunIntensityInput'),
        sunDayEl: get('sunDay'),
        sunMonthEl: get('sunMonth'),
        sunNorthEl: get('sunNorth'),
        sunEnabledEl: get('sunEnabled'),
        sunControlsEl: get('sunControls'),

        // Side panel sections
        imagesDetails: get('imagesDetails'),
        bindLogDetails: get('bindLogDetails'),

        // Environment / HDRI
        iblChk: get('hdriChk'),
        hdriPresetSel: get('hdriPreset'),
        iblIntEl: get('iblInt'),
        iblGammaEl: get('iblGamma'),
        iblTintEl: get('iblTint'),
        iblRotEl: get('iblRot'),
        hdriExposureEl: get('hdriExposure'),
        hdriSaturationEl: get('hdriSaturation'),
        hdriBlurEl: get('hdriBlur'),

        // Hemi light
        hemiIntEl: get('hemiInt'),
        hemiSkyEl: get('hemiSky'),
        hemiGroundEl: get('hemiGround'),

        // Appbar / buttons
        toggleSideBtn: get('toggleSideBtn'),
        loadParcelsBtn: get('loadParcelsBtn'),
        resetViewerBtn: get('resetViewerBtn'),
        resetViewBtn: get('resetViewBtn'),
        focusPickBtn: get('focusPickBtn'),
        exportBtn: get('exportBtn'),
        orderBtn: get('orderBtn'),
        fullscreenBtn: get('fullscreenBtn'),
        statsBtn: get('statsBtn'),
        vrToggleBtn: get('vrToggleBtn'),
        bgToggleBtn: get('bgToggleBtn'),
	        camsToggleBtn: get('camsToggleBtn'),
            collabPanelBtn: get('collabPanelBtn'),
	        collToggleBtn: get('collToggleBtn'),
	        solidToggleBtn: get('solidToggleBtn'),
	        vpmToggleBtn: get('vpmToggleBtn'),
	        npmToggleBtn: get('npmToggleBtn'),
	        gridToggleBtn: get('gridToggleBtn'),
	        statsOverlayEl: get('statsOverlay'),

        // Cameras
        camsBarEl: get('camsBar'),
        camsBarListEl: get('camsBarList'),
        camsDetailsEl: get('camsDetails'),
        camsCountEl: get('camsCount'),
        camsSideListEl: get('camsSideList'),
        camPropsDetailsEl: get('camPropsDetails'),
        camPropsTitleEl: get('camPropsTitle'),
        camPropsPanelEl: get('camPropsPanel'),

        // Collaboration
        collabDetailsEl: get('collabDetails'),
        collabDrawerEl: get('collabDrawer'),
        collabDrawerCloseBtn: get('collabDrawerClose'),
        collabAuthPanelEl: get('collabAuthPanel'),
        collabRoomEntryIntroEl: get('collabRoomEntryIntro'),
        collabEntryProjectEl: get('collabEntryProject'),
        collabEntryRoomEl: get('collabEntryRoom'),
        collabStatusEl: get('collabStatus'),
        collabNameEl: get('collabName'),
        collabEmailEl: get('collabEmail'),
        collabPasswordEl: get('collabPassword'),
        collabPasswordConfirmEl: get('collabPasswordConfirm'),
        collabEmailErrorEl: get('collabEmailError'),
        collabNameErrorEl: get('collabNameError'),
        collabPasswordErrorEl: get('collabPasswordError'),
        collabPasswordConfirmErrorEl: get('collabPasswordConfirmError'),
        collabAuthErrorEl: get('collabAuthError'),
        collabShowLoginBtn: get('collabShowLoginBtn'),
        collabShowRegisterBtn: get('collabShowRegisterBtn'),
        collabBackBtns: Array.from(document.querySelectorAll('.collab-back')),
        collabJoinBtn: get('collabJoinBtn'),
        collabSignupBtn: get('collabSignupBtn'),
        collabGuestBtn: get('collabGuestBtn'),
        collabResetBtn: get('collabResetBtn'),
        collabResendBtn: get('collabResendBtn'),
        collabFooterEl: get('collabFooter'),
        collabFooterGuestEl: get('collabFooterGuest'),
        collabFooterRegisteredEl: get('collabFooterRegistered'),
        collabFooterProjectNameEl: get('collabFooterProjectName'),
        collabFooterRoomNameEl: get('collabFooterRoomName'),
        collabStatusBtn: get('collabStatusBtn'),
        voiceJoinBtn: get('voiceJoinBtn'),
        voiceMuteBtn: get('voiceMuteBtn'),
        voiceAudioMountEl: get('voiceAudioMount'),
        collabChatPanelEl: get('collabChatPanel'),
        collabChatToggleBtn: get('collabChatToggleBtn'),
        collabProjectSelectEl: get('collabProjectSelect'),
        collabProjectCreateEl: get('collabProjectCreate'),
        collabProjectNameInputEl: get('collabProjectNameInput'),
        collabRoomSelectEl: get('collabRoomSelect'),
        collabRoomCreateEl: get('collabRoomCreate'),
        collabRoomNameInputEl: get('collabRoomNameInput'),
        collabRoomLinkEl: get('collabRoomLink'),
        collabCopyBtn: get('collabCopyBtn'),
        collabReserveBtn: get('collabReserveBtn'),
        collabOwnerEl: get('collabOwner'),
        collabParticipantsEl: get('collabParticipants'),
        collabChatLogEl: get('collabChatLog'),
        collabChatInputEl: get('collabChatInput'),
        collabChatSendBtn: get('collabChatSend'),
        collabChatParticipantsEl: get('collabChatParticipants'),

        // Glass controls
        glassOpacityEl: get('glassOpacity'),
        glassIorEl: get('glassIor'),
        glassTransmissionEl: get('glassTransmission'),
        glassReflectEl: get('glassReflect'),
        glassRoughEl: get('glassRough'),
        glassMetalEl: get('glassMetal'),
        glassAttenDistEl: get('glassAttenDist'),
        glassAttenColorEl: get('glassAttenColor'),
        glassColorEl: get('glassColor'),
        glassResetBtn: get('glassReset'),

        // Materials panel / gallery
        outEl: get('out'),
        galleryEl: get('gallery'),
        texCountEl: get('texCount'),
        matSelect: get('matSelect'),
        bindLogEl: get('bindLog'),
        bgAlphaEl: get('bgAlpha'),
        sampleSelect: get('sampleSelect'),

        // Imported lights UI
        lightHelpersBtn: get('lightHelpersBtn'),
        lightEmittersBtn: get('lightEmittersBtn'),

        // Texture modal
        texModal: get('texModal'),
        mClose: get('mClose'),
        mImg: get('mImg'),
        mTitle: get('mTitle'),
        mFile: get('mFile'),
        mKind: get('mKind'),
        mMime: get('mMime'),
        dlLink: get('dlLink'),
        bindBtn: get('bindBtn'),
        slotSelect: get('slotSelect'),

        // Prompt modal
        promptModalEl: get('promptModal'),
        promptTitleEl: get('promptTitle'),
        promptInputEl: get('promptInput'),
        promptOkBtn: get('promptOk'),
        promptCancelBtn: get('promptCancel'),
        promptCloseBtn: get('promptClose'),

        // Confirm modal
        confirmModalEl: get('confirmModal'),
        confirmTitleEl: get('confirmTitle'),
        confirmMessageEl: get('confirmMessage'),
        confirmOkBtn: get('confirmOk'),
        confirmCancelBtn: get('confirmCancel'),
        confirmCloseBtn: get('confirmClose'),

        // Password reset modal
        resetModalEl: get('resetModal'),
        resetTitleEl: get('resetTitle'),
        resetMessageEl: get('resetMessage'),
        resetPasswordEl: get('resetPassword'),
        resetPasswordRepeatEl: get('resetPasswordRepeat'),
        resetOkBtn: get('resetOk'),
        resetCancelBtn: get('resetCancel'),
        resetCloseBtn: get('resetClose'),

        // Transition modal
        transitionModalEl: get('transitionModal'),
        transitionTitleEl: get('transitionTitle'),
        transitionSecondsEl: get('transitionSeconds'),
        transitionTypeEl: get('transitionType'),
        transitionTrajectoryEl: get('transitionTrajectory'),
        transitionOkBtn: get('transitionOk'),
        transitionCancelBtn: get('transitionCancel'),
        transitionCloseBtn: get('transitionClose'),

        // Export modal
        exportModalEl: get('exportModal'),
        exportTitleEl: get('exportTitle'),
        exportFormatEl: get('exportFormat'),
        exportCoordsEl: get('exportCoords'),
        exportOkBtn: get('exportOk'),
        exportCancelBtn: get('exportCancel'),
        exportCloseBtn: get('exportClose'),

        // Order modal
        orderModalEl: get('orderModal'),

        // Rect annotation modal
        rectAnnotModalEl: get('rectAnnotModal'),
        rectAnnotTitleEl: get('rectAnnotTitle'),
        rectAnnotCloseBtn: get('rectAnnotClose'),
        rectAnnotColorEl: get('rectAnnotColor'),
        rectAnnotFillRowEl: get('rectAnnotFillRow'),
        rectAnnotFillEl: get('rectAnnotFill'),
        rectAnnotInfoRowEl: get('rectAnnotInfoRow'),
        rectAnnotInfoEl: get('rectAnnotInfo'),
        rectAnnotAreaEl: get('rectAnnotAreaRow'),
        rectAnnotTextEl: get('rectAnnotText'),
        rectAnnotTextRowEl: get('rectAnnotTextRow'),
        rectAnnotOkBtn: get('rectAnnotOk'),
        rectAnnotCancelBtn: get('rectAnnotCancel'),

        // File flow
        fileInput: get('fileInput'),
        openBtn: get('openBtn'),
    };
}
